In [4]:
import tushare as ts
from jqdatasdk import *
auth('19983410356','Q1569517810q')
# get_account_info()

In [11]:
#.XSHG 上交所
#XSHE 深交所
df = get_price('000001.XSHE',count=100, end_date='2023-05-21', frequency='1d')
df

             open  close   high    low       volume         money
2022-12-19  13.01  12.73  13.15  12.64  105598725.0  1.355436e+09
2022-12-20  12.66  12.46  12.77  12.37   91805204.0  1.150631e+09
2022-12-21  12.54  12.58  12.68  12.44   62956658.0  7.917825e+08
2022-12-22  12.69  12.64  12.84  12.59   68877989.0  8.761598e+08
2022-12-23  12.54  12.67  12.75  12.50   57818092.0  7.307060e+08
...           ...    ...    ...    ...          ...           ...
2023-05-15  12.38  12.52  12.54  12.15   95094801.0  1.173804e+09
2023-05-16  12.50  12.32  12.61  12.27  102262932.0  1.267712e+09
2023-05-17  12.28  12.19  12.34  12.14   77301057.0  9.453152e+08
2023-05-18  12.27  12.19  12.34  12.13   70393294.0  8.613475e+08
2023-05-19  12.13  12.05  12.14  12.03   70518964.0  8.511656e+08

[100 rows x 6 columns]

In [37]:
import time

In [39]:
#获取所有A股的行情信息
get_all_securities(['stock'])
stocks=list(get_all_securities(['stock']).index)
# print(stocks)
# df = get_price(stocks,count=10, end_date='2023-05-21', frequency='1d',panel=True)
for stock_code in stocks:
    print('正在获取行情数据，股票代码：',stock_code)
    df=get_price(stock_code,count=10, end_date='2023-05-21', frequency='1d',panel=True)
    print(df)
    time.sleep(0.1)

正在获取行情数据，股票代码： 000001.XSHE
             open  close   high    low       volume         money
2023-05-08  12.63  13.00  13.17  12.53  269482663.0  3.478892e+09
2023-05-09  13.08  12.85  13.28  12.82  248156923.0  3.238716e+09
2023-05-10  12.86  12.53  12.94  12.50  126719916.0  1.600190e+09
2023-05-11  12.64  12.54  12.81  12.50   92578214.0  1.166479e+09
2023-05-12  12.52  12.32  12.56  12.31   90718497.0  1.124579e+09
2023-05-15  12.38  12.52  12.54  12.15   95094801.0  1.173804e+09
2023-05-16  12.50  12.32  12.61  12.27  102262932.0  1.267712e+09
2023-05-17  12.28  12.19  12.34  12.14   77301057.0  9.453152e+08
2023-05-18  12.27  12.19  12.34  12.13   70393294.0  8.613475e+08
2023-05-19  12.13  12.05  12.14  12.03   70518964.0  8.511656e+08
正在获取行情数据，股票代码： 000002.XSHE
             open  close   high    low       volume         money
2023-05-08  15.38  15.58  15.60  15.13  103391563.0  1.590720e+09
2023-05-09  15.50  15.47  15.89  15.41  125984623.0  1.975640e+09
2023-05-10  15.46  15.30  15.50  15.16   65902998.0  1.005441e+09
2023-05-11  15.30  15.30  15.36  15.21   44334679.0  6.771226e+08
2023-05-12  15.24  15.06  15.34  15.06   46952953.0  7.116491e+08
2023-05-15  15.00  15.06  15.10  14.81   65548434.0  9.778807e+08
2023-05-16  15.06  14.91  15.12  14.88   37484203.0  5.606299e+08
2023-05-17  14.88  14.78  14.93  14.68   50646150.0  7.499776e+08
2023-05-18  14.82  14.62  14.87  14.53   57683517.0  8.470451e+08
2023-05-19  14.62  14.54  14.62  14.50   39628837.0  5.759416e+08
正在获取行情数据，股票代码： 000004.XSHE
             open  close   high    low     volume       money
2023-05-08  11.14  10.68  11.38  10.68  3124236.0  34235850.0
2023-05-09  10.39  10.15  10.47  10.15  5388800.0  55037730.0
2023-05-10  10.15  10.22  10.37  10.09  1823600.0  18679571.0
2023-05-11  10.37  10.61  10.73  10.37  3473861.0  37088156.0
2023-05-12  10.63  10.66  10.87  10.61  2227506.0  23840289.0
2023-05-15  10.74  10.77  10.77  10.53  1204000.0  12826717.0
2023-05-16  10.70  10.24  10.73  10.23  3292590.0  33917171.0
2023-05-17  10.12  10.28  10.42  10.02  1610300.0  16557189.0
2023-05-18  10.24  10.74  10.74  10.24  2442390.0  25808783.0
2023-05-19  10.74  10.81  10.87  10.56  2065001.0  22122181.0
正在获取行情数据，股票代码： 000005.XSHE
            open  close  high   low      volume       money
2023-05-08  1.65   1.58  1.66  1.58  13525991.0  21621291.0
2023-05-09  1.54   1.50  1.56  1.50  15740207.0  23725054.0
2023-05-10  1.44   1.46  1.47  1.43  16411920.0  23664498.0
2023-05-11  1.46   1.51  1.52  1.45   9772550.0  14622658.0
2023-05-12  1.50   1.48  1.51  1.47   5069400.0   7548520.0
2023-05-15  1.48   1.47  1.49  1.44   5461700.0   8000265.0
2023-05-16  1.46   1.45  1.46  1.44   3126600.0   4534681.0
2023-05-17  1.45   1.47  1.50  1.44   3949848.0   5834775.0
2023-05-18  1.48   1.49  1.50  1.47   3349654.0   4972881.0
2023-05-19  1.48   1.47  1.49  1.46   4772901.0   7008324.0
正在获取行情数据，股票代码： 000006.XSHE
            open  close  high   low      volume        money
2023-05-08  4.76   4.81  4.83  4.69  22654025.0  107974440.0
2023-05-09  4.79   4.78  4.91  4.78  18004105.0   87184864.0
2023-05-10  4.79   4.92  5.03  4.71  33441205.0  162579249.0
2023-05-11  4.82   4.79  4.91  4.74  32847948.0  157797888.0
2023-05-12  4.76   4.71  4.80  4.71  16296847.0   77338339.0
2023-05-15  4.69   4.72  4.74  4.62  16087646.0   75256229.0
2023-05-16  4.73   4.62  4.73  4.61  12638987.0   58785366.0
2023-05-17  4.59   4.62  4.65  4.56   7533379.0   34826700.0
2023-05-18  4.61   4.62  4.67  4.61  10047999.0   46564692.0
2023-05-19  4.63   4.56  4.63  4.54  11217556.0   51208161.0
正在获取行情数据，股票代码： 000007.XSHE
            open  close  high   low      volume       money
2023-05-08  4.92   4.92  4.92  4.92    479300.0   2358156.0
2023-05-09  4.67   4.67  4.67  4.67    413400.0   1930578.0
2023-05-10  4.44   4.44  4.44  4.44    604400.0   2683536.0
2023-05-11  4.22   4.22  4.43  4.22  23093840.0  98536638.0
2023-05-12  4.34   4.15  4.43  4.03  18935287.0  80586510.0
2023-05-15  3.95   4.02  4.09  3.95   8373150.0  33589843.0
2023-05-16  3.99   4.08  4.08  3.99   2971679.0  11994981.0
2023-05-17  4.04   4.18  4.25  4.04   5286440.0  21902582.0
2023-05-18  4.13   4.36  4.39  4.13   8930646.0  38661268.0
2023-05-19  4.35   4.54  4.56  4.28   8422645.0  37284181.0
正在获取行情数据，股票代码： 000008.XSHE
            open  close  high   low      volume        money
2023-05-08  2.49   2.50  2.52  2.45  47823476.0  118868824.0
2023-05-09  2.49   2.49  2.54  2.48  40627565.0  102045511.0
2023-05-10  2.49   2.47  2.50  2.45  21311700.0   52658957.0
2023-05-11  2.47   2.51  2.51  2.46  20300951.0   50604461.0
2023-05-12  2.50   2.47  2.50  2.47  16180335.0   40161551.0
2023-05-15  2.48   2.47  2.49  2.43  23615565.0   57928587.0
2023-05-16  2.47   2.43  2.48  2.42  20301215.0   49611260.0
2023-05-17  2.42   2.45  2.45  2.40  17358910.0   42192533.0
2023-05-18  2.48   2.47  2.50  2.45  20355920.0   50325124.0
2023-05-19  2.46   2.44  2.47  2.43  17326669.0   42308716.0

KeyboardInterrupt:

In [34]:
df

,time,code,open,close,high,low,volume,money
0,2023-05-08,002233.XSHE,8.16,8.13,8.25,8.07,12332104.0,100240796.0
1,2023-05-09,002233.XSHE,8.15,8.08,8.28,8.08,12656627.0,103527605.0
2,2023-05-10,002233.XSHE,8.08,8.09,8.15,8.04,6713880.0,54252343.0
3,2023-05-11,002233.XSHE,8.07,8.08,8.09,7.98,5219908.0,42047168.0
4,2023-05-12,002233.XSHE,8.05,7.98,8.10,7.96,7105300.0,56961366.0
...,...,...,...,...,...,...,...,...
52565,2023-05-15,603566.XSHG,27.10,25.73,27.38,25.40,6326833.0,164051565.0
52566,2023-05-16,603566.XSHG,25.85,25.34,26.03,25.03,4134450.0,105095880.0
52567,2023-05-17,603566.XSHG,25.28,26.00,26.08,25.28,2728734.0,70416072.0
52568,2023-05-18,603566.XSHG,25.94,25.14,26.13,25.09,3096757.0,78777286.0
52569,2023-05-19,603566.XSHG,25.14,25.47,25.70,24.94,2642835.0,67244930.0