In [3]:
# import tushare as ts
from jqdatasdk import *
auth('19983410356','Q1569517810q')
# get_account_info()

In [11]:
#.XSHG 上交所
#XSHE 深交所
df = get_price('000001.XSHE',count=100, end_date='2023-05-21', frequency='1d')
df

             open  close   high    low       volume         money
2022-12-19  13.01  12.73  13.15  12.64  105598725.0  1.355436e+09
2022-12-20  12.66  12.46  12.77  12.37   91805204.0  1.150631e+09
2022-12-21  12.54  12.58  12.68  12.44   62956658.0  7.917825e+08
2022-12-22  12.69  12.64  12.84  12.59   68877989.0  8.761598e+08
2022-12-23  12.54  12.67  12.75  12.50   57818092.0  7.307060e+08
...           ...    ...    ...    ...          ...           ...
2023-05-15  12.38  12.52  12.54  12.15   95094801.0  1.173804e+09
2023-05-16  12.50  12.32  12.61  12.27  102262932.0  1.267712e+09
2023-05-17  12.28  12.19  12.34  12.14   77301057.0  9.453152e+08
2023-05-18  12.27  12.19  12.34  12.13   70393294.0  8.613475e+08
2023-05-19  12.13  12.05  12.14  12.03   70518964.0  8.511656e+08

[100 rows x 6 columns]

In [37]:
import time

In [39]:
#获取所有A股的行情信息
get_all_securities(['stock'])
stocks=list(get_all_securities(['stock']).index)
# print(stocks)
# df = get_price(stocks,count=10, end_date='2023-05-21', frequency='1d',panel=True)
for stock_code in stocks:
    print('正在获取行情数据，股票代码：',stock_code)
    df=get_price(stock_code,count=10, end_date='2023-05-21', frequency='1d',panel=True)
    print(df)
    time.sleep(0.1)

正在获取行情数据，股票代码： 000001.XSHE
             open  close   high    low       volume         money
2023-05-08  12.63  13.00  13.17  12.53  269482663.0  3.478892e+09
2023-05-09  13.08  12.85  13.28  12.82  248156923.0  3.238716e+09
2023-05-10  12.86  12.53  12.94  12.50  126719916.0  1.600190e+09
2023-05-11  12.64  12.54  12.81  12.50   92578214.0  1.166479e+09
2023-05-12  12.52  12.32  12.56  12.31   90718497.0  1.124579e+09
2023-05-15  12.38  12.52  12.54  12.15   95094801.0  1.173804e+09
2023-05-16  12.50  12.32  12.61  12.27  102262932.0  1.267712e+09
2023-05-17  12.28  12.19  12.34  12.14   77301057.0  9.453152e+08
2023-05-18  12.27  12.19  12.34  12.13   70393294.0  8.613475e+08
2023-05-19  12.13  12.05  12.14  12.03   70518964.0  8.511656e+08
正在获取行情数据，股票代码： 000002.XSHE
             open  close   high    low       volume         money
2023-05-08  15.38  15.58  15.60  15.13  103391563.0  1.590720e+09
2023-05-09  15.50  15.47  15.89  15.41  125984623.0  1.975640e+09
2023-05-10  15.46  15.30  15.50  15.16   65902998.0  1.005441e+09
2023-05-11  15.30  15.30  15.36  15.21   44334679.0  6.771226e+08
2023-05-12  15.24  15.06  15.34  15.06   46952953.0  7.116491e+08
2023-05-15  15.00  15.06  15.10  14.81   65548434.0  9.778807e+08
2023-05-16  15.06  14.91  15.12  14.88   37484203.0  5.606299e+08
2023-05-17  14.88  14.78  14.93  14.68   50646150.0  7.499776e+08
2023-05-18  14.82  14.62  14.87  14.53   57683517.0  8.470451e+08
2023-05-19  14.62  14.54  14.62  14.50   39628837.0  5.759416e+08
正在获取行情数据，股票代码： 000004.XSHE
             open  close   high    low     volume       money
2023-05-08  11.14  10.68  11.38  10.68  3124236.0  34235850.0
2023-05-09  10.39  10.15  10.47  10.15  5388800.0  55037730.0
2023-05-10  10.15  10.22  10.37  10.09  1823600.0  18679571.0
2023-05-11  10.37  10.61  10.73  10.37  3473861.0  37088156.0
2023-05-12  10.63  10.66  10.87  10.61  2227506.0  23840289.0
2023-05-15  10.74  10.77  10.77  10.53  1204000.0  12826717.0
2023-05-16  10.70  10.24  10.73  10.23  3292590.0  33917171.0
2023-05-17  10.12  10.28  10.42  10.02  1610300.0  16557189.0
2023-05-18  10.24  10.74  10.74  10.24  2442390.0  25808783.0
2023-05-19  10.74  10.81  10.87  10.56  2065001.0  22122181.0
正在获取行情数据，股票代码： 000005.XSHE
            open  close  high   low      volume       money
2023-05-08  1.65   1.58  1.66  1.58  13525991.0  21621291.0
2023-05-09  1.54   1.50  1.56  1.50  15740207.0  23725054.0
2023-05-10  1.44   1.46  1.47  1.43  16411920.0  23664498.0
2023-05-11  1.46   1.51  1.52  1.45   9772550.0  14622658.0
2023-05-12  1.50   1.48  1.51  1.47   5069400.0   7548520.0
2023-05-15  1.48   1.47  1.49  1.44   5461700.0   8000265.0
2023-05-16  1.46   1.45  1.46  1.44   3126600.0   4534681.0
2023-05-17  1.45   1.47  1.50  1.44   3949848.0   5834775.0
2023-05-18  1.48   1.49  1.50  1.47   3349654.0   4972881.0
2023-05-19  1.48   1.47  1.49  1.46   4772901.0   7008324.0
正在获取行情数据，股票代码： 000006.XSHE
            open  close  high   low      volume        money
2023-05-08  4.76   4.81  4.83  4.69  22654025.0  107974440.0
2023-05-09  4.79   4.78  4.91  4.78  18004105.0   87184864.0
2023-05-10  4.79   4.92  5.03  4.71  33441205.0  162579249.0
2023-05-11  4.82   4.79  4.91  4.74  32847948.0  157797888.0
2023-05-12  4.76   4.71  4.80  4.71  16296847.0   77338339.0
2023-05-15  4.69   4.72  4.74  4.62  16087646.0   75256229.0
2023-05-16  4.73   4.62  4.73  4.61  12638987.0   58785366.0
2023-05-17  4.59   4.62  4.65  4.56   7533379.0   34826700.0
2023-05-18  4.61   4.62  4.67  4.61  10047999.0   46564692.0
2023-05-19  4.63   4.56  4.63  4.54  11217556.0   51208161.0
正在获取行情数据，股票代码： 000007.XSHE
            open  close  high   low      volume       money
2023-05-08  4.92   4.92  4.92  4.92    479300.0   2358156.0
2023-05-09  4.67   4.67  4.67  4.67    413400.0   1930578.0
2023-05-10  4.44   4.44  4.44  4.44    604400.0   2683536.0
2023-05-11  4.22   4.22  4.43  4.22  23093840.0  98536638.0
2023-05-12  4.34   4.15  4.43  4.03  18935287.0  80586510.0
2023-05-15  3.95   4.02  4.09  3.95   8373150.0  33589843.0
2023-05-16  3.99   4.08  4.08  3.99   2971679.0  11994981.0
2023-05-17  4.04   4.18  4.25  4.04   5286440.0  21902582.0
2023-05-18  4.13   4.36  4.39  4.13   8930646.0  38661268.0
2023-05-19  4.35   4.54  4.56  4.28   8422645.0  37284181.0
正在获取行情数据，股票代码： 000008.XSHE
            open  close  high   low      volume        money
2023-05-08  2.49   2.50  2.52  2.45  47823476.0  118868824.0
2023-05-09  2.49   2.49  2.54  2.48  40627565.0  102045511.0
2023-05-10  2.49   2.47  2.50  2.45  21311700.0   52658957.0
2023-05-11  2.47   2.51  2.51  2.46  20300951.0   50604461.0
2023-05-12  2.50   2.47  2.50  2.47  16180335.0   40161551.0
2023-05-15  2.48   2.47  2.49  2.43  23615565.0   57928587.0
2023-05-16  2.47   2.43  2.48  2.42  20301215.0   49611260.0
2023-05-17  2.42   2.45  2.45  2.40  17358910.0   42192533.0
2023-05-18  2.48   2.47  2.50  2.45  20355920.0   50325124.0
2023-05-19  2.46   2.44  2.47  2.43  17326669.0   42308716.0

KeyboardInterrupt:

In [34]:
df

,time,code,open,close,high,low,volume,money
0,2023-05-08,002233.XSHE,8.16,8.13,8.25,8.07,12332104.0,100240796.0
1,2023-05-09,002233.XSHE,8.15,8.08,8.28,8.08,12656627.0,103527605.0
2,2023-05-10,002233.XSHE,8.08,8.09,8.15,8.04,6713880.0,54252343.0
3,2023-05-11,002233.XSHE,8.07,8.08,8.09,7.98,5219908.0,42047168.0
4,2023-05-12,002233.XSHE,8.05,7.98,8.10,7.96,7105300.0,56961366.0
...,...,...,...,...,...,...,...,...
52565,2023-05-15,603566.XSHG,27.10,25.73,27.38,25.40,6326833.0,164051565.0
52566,2023-05-16,603566.XSHG,25.85,25.34,26.03,25.03,4134450.0,105095880.0
52567,2023-05-17,603566.XSHG,25.28,26.00,26.08,25.28,2728734.0,70416072.0
52568,2023-05-18,603566.XSHG,25.94,25.14,26.13,25.09,3096757.0,78777286.0
52569,2023-05-19,603566.XSHG,25.14,25.47,25.70,24.94,2642835.0,67244930.0

In [2]:
#resample函数的使用
#日K转换为周K
#汇总统计：统计一下月成交量、成交额（sum)
import pandas as pd

In [6]:
index = pd.date_range('20000101',periods=9,freq='T')
series = pd.Series(range(9),index=index)
series

2000-01-01 00:00:00    0
2000-01-01 00:01:00    1
2000-01-01 00:02:00    2
2000-01-01 00:03:00    3
2000-01-01 00:04:00    4
2000-01-01 00:05:00    5
2000-01-01 00:06:00    6
2000-01-01 00:07:00    7
2000-01-01 00:08:00    8
Freq: T, dtype: int64

In [9]:
series.resample('3T').sum()

2000-01-01 00:00:00     3
2000-01-01 00:03:00    12
2000-01-01 00:06:00    21
Freq: 3T, dtype: int64

In [45]:
series.resample('3T',closed='right',label='right').sum()

2000-01-01 00:00:00     0
2000-01-01 00:03:00     6
2000-01-01 00:06:00    15
2000-01-01 00:09:00    15
Freq: 3T, dtype: int64

In [62]:
#设置行列不忽略
pd.set_option('display.max_rows',200)
pd.set_option('display.max_columns',20)

In [68]:
#转换周期：日K转换为周K
#获取日K
#获取周K（当周的）：开盘价（当周的第一天）、收盘价(当周的最后一天)、最高价（当周）、最低价（当周）
df = get_price('000001.XSHE',count=100,end_date='2023-05-21', frequency='1d',panel=False)
df['weekday']=df.index.weekday
df

             open  close   high    low       volume         money  weekday
2022-12-19  13.01  12.73  13.15  12.64  105598725.0  1.355436e+09        0
2022-12-20  12.66  12.46  12.77  12.37   91805204.0  1.150631e+09        1
2022-12-21  12.54  12.58  12.68  12.44   62956658.0  7.917825e+08        2
2022-12-22  12.69  12.64  12.84  12.59   68877989.0  8.761598e+08        3
2022-12-23  12.54  12.67  12.75  12.50   57818092.0  7.307060e+08        4
2022-12-26  12.68  12.47  12.73  12.41   81654489.0  1.021904e+09        0
2022-12-27  12.56  12.80  12.91  12.56   90759517.0  1.160090e+09        1
2022-12-28  12.85  12.83  13.06  12.69   81047255.0  1.042402e+09        2
2022-12-29  12.76  12.72  12.82  12.54   68314154.0  8.651450e+08        3
2022-12-30  12.73  12.85  12.96  12.65   83797071.0  1.074757e+09        4
2023-01-03  12.89  13.44  13.52  12.74  224759667.0  2.971547e+09        1
2023-01-04  13.38  13.98  14.08  13.31  224304293.0  3.110729e+09        2
2023-01-05  14.06  14.14  14.39  14.03  170600995.0  2.417272e+09        3
2023-01-06  14.16  14.27  14.37  14.14  122488383.0  1.747915e+09        4
2023-01-09  14.40  14.45  14.53  14.17  108343322.0  1.561368e+09        0
2023-01-10  14.41  14.10  14.54  14.05  130035799.0  1.851094e+09        1
2023-01-11  14.11  14.32  14.43  14.05   85080620.0  1.217451e+09        2
2023-01-12  14.42  14.32  14.42  14.18   64094241.0  9.143677e+08        3
2023-01-13  14.32  14.59  14.59  14.20   97221412.0  1.407181e+09        4
2023-01-16  14.59  14.72  14.92  14.50  159805652.0  2.356400e+09        0
2023-01-17  14.77  14.61  14.82  14.42   95863990.0  1.396152e+09        1
2023-01-18  14.59  14.75  14.82  14.56   73594156.0  1.083363e+09        2
2023-01-19  14.77  14.73  14.89  14.52   65751707.0  9.637446e+08        3
2023-01-20  14.80  14.77  14.88  14.64   62342082.0  9.201448e+08        4
2023-01-30  15.23  14.79  15.37  14.54  140780826.0  2.096868e+09        0
2023-01-31  14.88  14.63  15.14  14.60  105561006.0  1.568639e+09        1
2023-02-01  14.67  14.35  14.72  14.16  169371373.0  2.426472e+09        2
2023-02-02  14.39  14.25  14.43  13.93  161635227.0  2.280745e+09        3
2023-02-03  14.11  13.98  14.20  13.82  127675610.0  1.782106e+09        4
2023-02-06  13.76  13.67  13.79  13.53  134971896.0  1.838429e+09        0
2023-02-07  13.73  13.87  13.98  13.70   89064835.0  1.235298e+09        1
2023-02-08  13.90  13.71  13.98  13.70   67392476.0  9.287089e+08        2
2023-02-09  13.68  13.79  13.96  13.63   85058483.0  1.174362e+09        3
2023-02-10  13.76  13.65  13.78  13.53   86793113.0  1.184283e+09        4
2023-02-13  13.61  13.49  13.61  13.28  184391970.0  2.473405e+09        0
2023-02-14  13.52  13.63  13.65  13.47   93211136.0  1.263892e+09        1
2023-02-15  13.62  13.34  13.63  13.30  128071119.0  1.713567e+09        2
2023-02-16  13.35  13.28  13.58  13.18  131029426.0  1.757431e+09        3
2023-02-17  13.31  13.11  13.39  13.11   94074331.0  1.246777e+09        4
2023-02-20  13.18  13.81  13.81  13.17  216776066.0  2.945970e+09        0
2023-02-21  13.73  13.76  13.86  13.59  101463238.0  1.393153e+09        1
2023-02-22  13.67  13.69  13.78  13.61   65449230.0  8.957425e+08        2
2023-02-23  13.67  13.72  13.98  13.65   84458270.0  1.165540e+09        3
2023-02-24  13.69  13.53  13.70  13.47   74777815.0  1.012653e+09        4
2023-02-27  13.42  13.36  13.55  13.35   63660634.0  8.548540e+08        0
2023-02-28  13.42  13.45  13.52  13.29   62275072.0  8.333160e+08        1
2023-03-01  13.47  13.83  13.85  13.41  125326609.0  1.719711e+09        2
2023-03-02  13.79  13.90  14.10  13.73  104063276.0  1.447566e+09        3
2023-03-03  14.01  13.95  14.03  13.80   70779227.0  9.855521e+08        4
2023-03-06  13.96  13.52  13.96  13.39  149130114.0  2.023955e+09        0
2023-03-07  13.52  13.36  13.76  13.33  131044075.0  1.773655e+09        1
2023-03-08  13.31  13.21  13.32  13.08  112362823.0  1.479839e+09        2
2023-03-09  13.22  12.89  13.26  12.82  177837095.0  2.305766e+09        3
2023-03-10  12.69  12.83  12.95  12.69   87788025.0  1.128558e+09        4
2023-03-13  12.81  12.74  12.97  12.69  102501945.0  1.309490e+09        0
2023-03-14  12.68  12.56  12.69  12.43  117707742.0  1.474124e+09        1
2023-03-15  12.74  12.74  12.87  12.63  100322985.0  1.278262e+09        2
2023-03-16  12.58  12.52  12.72  12.50   93913382.0  1.182054e+09        3
2023-03-17  12.68  12.45  12.73  12.35  159475217.0  2.000832e+09        4
2023-03-20  12.46  12.27  12.54  12.25  121778661.0  1.505894e+09        0
2023-03-21  12.35  12.40  12.48  12.20   86123125.0  1.060914e+09        1
2023-03-22  12.45  12.49  12.57  12.41   89805486.0  1.121081e+09        2
2023-03-23  12.40  12.59  12.59  12.33   82390618.0  1.029380e+09        3
2023-03-24  12.54  12.52  12.55  12.46   63666455.0  7.963195e+08        4
2023-03-27  12.50  12.30  12.51  12.16  103299639.0  1.266945e+09        0
2023-03-28  12.36  12.34  12.43  12.25   69028994.0  8.517979e+08        1
2023-03-29  12.43  12.23  12.44  12.20   61058983.0  7.506876e+08        2
2023-03-30  12.25  12.38  12.41  12.11   84463962.0  1.035423e+09        3
2023-03-31  12.39  12.23  12.47  12.21   88658284.0  1.092263e+09        4
2023-04-03  12.25  12.37  12.39  12.16   75847238.0  9.342852e+08        0
2023-04-04  12.34  12.35  12.42  12.29   66323511.0  8.177265e+08        1
2023-04-06  12.30  12.28  12.31  12.20   57704888.0  7.064807e+08        3
2023-04-07  12.27  12.32  12.39  12.20   62273980.0  7.673548e+08        4
2023-04-10  12.34  12.38  12.40  12.28   65578241.0  8.099431e+08        0
2023-04-11  12.40  12.24  12.42  12.22   79673334.0  9.783029e+08        1
2023-04-12  12.28  12.18  12.29  12.15   93213182.0  1.136998e+09        2
2023-04-13  12.11  12.26  12.37  12.01  115916723.0  1.413919e+09        3
2023-04-14  12.30  12.39  12.59  12.28  132962569.0  1.653540e+09        4
2023-04-17  12.36  12.62  12.63  12.30  133599496.0  1.669358e+09        0
2023-04-18  12.62  12.69  12.89  12.58  157643851.0  2.009935e+09        1
2023-04-19  12.71  12.54  12.76  12.52  103909754.0  1.309536e+09        2
2023-04-20  12.59  12.45  12.59  12.32   83157089.0  1.033331e+09        3
2023-04-21  12.40  12.20  12.52  12.18   94105543.0  1.160510e+09        4
2023-04-24  12.18  11.81  12.20  11.74  150343764.0  1.798134e+09        0
2023-04-25  11.85  11.99  12.08  11.83  133362686.0  1.595320e+09        1
2023-04-26  11.96  11.83  11.96  11.70  101541644.0  1.197556e+09        2
2023-04-27  11.77  11.97  12.06  11.71  102856214.0  1.222756e+09        3
2023-04-28  11.97  12.25  12.48  11.93  148047376.0  1.816868e+09        4
2023-05-04  12.11  12.43  12.52  11.90  151428822.0  1.863146e+09        3
2023-05-05  12.48  12.60  12.80  12.45  180513145.0  2.283981e+09        4
2023-05-08  12.63  13.00  13.17  12.53  269482663.0  3.478892e+09        0
2023-05-09  13.08  12.85  13.28  12.82  248156923.0  3.238716e+09        1
2023-05-10  12.86  12.53  12.94  12.50  126719916.0  1.600190e+09        2
2023-05-11  12.64  12.54  12.81  12.50   92578214.0  1.166479e+09        3
2023-05-12  12.52  12.32  12.56  12.31   90718497.0  1.124579e+09        4
2023-05-15  12.38  12.52  12.54  12.15   95094801.0  1.173804e+09        0
2023-05-16  12.50  12.32  12.61  12.27  102262932.0  1.267712e+09        1
2023-05-17  12.28  12.19  12.34  12.14   77301057.0  9.453152e+08        2
2023-05-18  12.27  12.19  12.34  12.13   70393294.0  8.613475e+08        3
2023-05-19  12.13  12.05  12.14  12.03   70518964.0  8.511656e+08        4

In [74]:
1.355436e+09+1.150631e+09+7.917825e+08+8.761598e+08+7.307060e+08

4904715300.0

In [69]:
df_week = pd.DataFrame()
df_week['open'] =df['open'].resample('W').first()
df_week['close'] =df['close'].resample('W').last()
df_week['high'] =df['high'].resample('W').max()
df_week['low'] =df['low'].resample('W').min()
df_week['weekday']=df_week.index.weekday
df_week

             open  close   high    low  weekday
2022-12-25  13.01  12.67  13.15  12.37        6
2023-01-01  12.68  12.85  13.06  12.41        6
2023-01-08  12.89  14.27  14.39  12.74        6
2023-01-15  14.40  14.59  14.59  14.05        6
2023-01-22  14.59  14.77  14.92  14.42        6
2023-01-29    NaN    NaN    NaN    NaN        6
2023-02-05  15.23  13.98  15.37  13.82        6
2023-02-12  13.76  13.65  13.98  13.53        6
2023-02-19  13.61  13.11  13.65  13.11        6
2023-02-26  13.18  13.53  13.98  13.17        6
2023-03-05  13.42  13.95  14.10  13.29        6
2023-03-12  13.96  12.83  13.96  12.69        6
2023-03-19  12.81  12.45  12.97  12.35        6
2023-03-26  12.46  12.52  12.59  12.20        6
2023-04-02  12.50  12.23  12.51  12.11        6
2023-04-09  12.25  12.32  12.42  12.16        6
2023-04-16  12.34  12.39  12.59  12.01        6
2023-04-23  12.36  12.20  12.89  12.18        6
2023-04-30  12.18  12.25  12.48  11.70        6
2023-05-07  12.11  12.60  12.80  11.90        6
2023-05-14  12.63  12.32  13.28  12.31        6
2023-05-21  12.38  12.05  12.61  12.03        6

In [70]:
#汇总统计：统计月成交量、成交额（sum）
df_week['volume_sum'] = df['volume'].resample('W').sum()
df_week['money_sum'] = df['money'].resample('W').sum()
df_week

             open  close   high    low  weekday   volume_sum     money_sum
2022-12-25  13.01  12.67  13.15  12.37        6  387056668.0  4.904715e+09
2023-01-01  12.68  12.85  13.06  12.41        6  405572486.0  5.164298e+09
2023-01-08  12.89  14.27  14.39  12.74        6  742153338.0  1.024746e+10
2023-01-15  14.40  14.59  14.59  14.05        6  484775394.0  6.951462e+09
2023-01-22  14.59  14.77  14.92  14.42        6  457357587.0  6.719804e+09
2023-01-29    NaN    NaN    NaN    NaN        6          0.0  0.000000e+00
2023-02-05  15.23  13.98  15.37  13.82        6  705024042.0  1.015483e+10
2023-02-12  13.76  13.65  13.98  13.53        6  463280803.0  6.361081e+09
2023-02-19  13.61  13.11  13.65  13.11        6  630777982.0  8.455072e+09
2023-02-26  13.18  13.53  13.98  13.17        6  542924619.0  7.413059e+09
2023-03-05  13.42  13.95  14.10  13.29        6  426104818.0  5.840999e+09
2023-03-12  13.96  12.83  13.96  12.69        6  658162132.0  8.711772e+09
2023-03-19  12.81  12.45  12.97  12.35        6  573921271.0  7.244763e+09
2023-03-26  12.46  12.52  12.59  12.20        6  443764345.0  5.513589e+09
2023-04-02  12.50  12.23  12.51  12.11        6  406509862.0  4.997117e+09
2023-04-09  12.25  12.32  12.42  12.16        6  262149617.0  3.225847e+09
2023-04-16  12.34  12.39  12.59  12.01        6  487344049.0  5.992702e+09
2023-04-23  12.36  12.20  12.89  12.18        6  572415733.0  7.182669e+09
2023-04-30  12.18  12.25  12.48  11.70        6  636151684.0  7.630634e+09
2023-05-07  12.11  12.60  12.80  11.90        6  331941967.0  4.147127e+09
2023-05-14  12.63  12.32  13.28  12.31        6  827656213.0  1.060886e+10
2023-05-21  12.38  12.05  12.61  12.03        6  415571048.0  5.099345e+09